version: '3.1'

services:

  adminer:
    image: adminer
    ports: 
      -18080:8080
    restart: always
    environment:
      ADMINER_PLUGINS: plugin designs tables-filter tinymce edit-calendar edit-foreign edit-textarea enum-option enum-types
      ADMINER_DESIGN: haeckel
      ADMINER_DEFAULT_SERVER: mariadb
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: mysql
    ports: 
      -13306:3306
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    secrets:
      - pwd-admin
      - pwd-root
    volumes:
      - /opt/mysql/conf:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pwd-root
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/pwd-admin
    deploy:
      mode: replicated
      replicas: 1
      
  mariadb:
    image: mariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    secrets:
      - pwd-admin
      - pwd-root
    volumes:
      - /opt/mariadb/conf:/etc/mysql/conf.d
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/pwd-root
      MYSQL_USER: admin
      MYSQL_PASSWORD_FILE: /run/secrets/pwd-admin
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres
    restart: always
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    secrets:
      - pwd-root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /opt/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pwd-root
      PGDATA: /var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - redis-data:/data
      - /opt/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      mode: replicated
      replicas: 1
  
  mongodb:
    image: mongo
    restart: always
    command: --config /etc/mongo/mongod.conf
    secrets:
      - pwd-root
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/pwd-root
    volumes:
      - /opt/mongodb/conf:/etc/mongo
      - mongo-data:/data/db 
    deploy:
      mode: replicated
      replicas: 1

volumes:
  mysql-data:
  mariadb-data:
  postgres-data:
  redis-data:
  mongo-data:

secrets:
  pwd-root:
    external: true
  pwd-admin:
    external: true